---
# File 00-ss-core/kustomization.yaml
# Core is used to deploy 1) Storage 2) Ambassador  5) Secrets
# local-path-provisioner
apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: ss-core
resources:
  - local-path-storage.yaml
  - aes.yaml
  - metallb.yaml
  - metallbconfig.yaml
  - qotm.yaml
  - quote-mapper.yaml
secretGenerator:
- name: memberlist
  literals:
  - secretkey=metallbsecret
