---
apiVersion: v1
data:
  config: |
    address-pools:
    - name: generic-cluster-pool
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250
kind: ConfigMap
metadata:
  name: config