---
# File : base/kustomization.yaml
# This is the master file which refers to all applicaions
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
  app.kubernetes.io/part-of: sock-shop
  environment: base
kind: Kustomization
resources:
  - namespaces.yaml
  - aes-crds.yaml
