---
# File overlays/prod/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - ../../base
commonLabels:
  environment: local
kind: Kustomization
patchesStrategicMerge:
  - custom-ip.yaml
  - ambassador-ip.yaml
  
patchesJson6902:
- target:
    version: v1
    kind: Service
    name: ambassador
  path: ambassador-patch.yaml